### ISSUE TITLE
Check various feature sets in CI

### ISSUE THREAD

**Issue by CosmicHorrorDev** [zeenix/tomling#22]
Currently it looks like CI is only testing the default feature set, but it'd be good to try building / running the test suite on some of our possible feature sets

**Comment by zeenix** [comment]
Well that was very much my plan. However, the crate docs example (from README) require the `cargo-toml` feature. I'm not sure if there's a good solution for this but what we can do is to run `cargo test --tests` for testing with features disabled.

**Comment by CosmicHorrorDev** [comment]
Hrm that's a good point. Would you be open to having the library docs copied out of the README, so that the doctests can be conditionally ignored without messing up the README's formatting? We can still conditionally run doctests on the README to ensure the code examples are still good

**Comment by zeenix** [comment]
Actually we could just do: 

 ```rust
 # #[cfg(feature = "cargo-toml")]
 # {

  # }
