### ISSUE TITLE
Consider testing parser against toml-test

### ISSUE THREAD

**Issue by CosmicHorrorDev** [zeenix/tomling#6]
TOML maintains [`toml-test`](https://github.com/toml-lang/toml-test), a suite of tests meant to test TOML parsers, and there are rust-specific helpers like [`toml-test-harness`](https://crates.io/crates/toml-test-harness). I would highly recommend testing against the official suite as it covers some of the tricker parts to get right like when it's valid to append to tables

**Comment by zeenix** [comment]
@CosmicHorrorDev thank you! I'll check it out.
