### ISSUE TITLE
Very slow parsing on small input

### ISSUE THREAD

**Issue by CosmicHorrorDev** [zeenix/tomling#8]
Running #7 for a bit tripped a timeout on some reasonably small input (48 seconds for me with a release build)

```rust
#[test]
fn slow() {
    let _ = tomling::parse("a=[[[[[[[[[[[[[[[[[[[[[[[[[[[");
}
```

**Comment by zeenix** [comment]
Very interesting. I've not yet done any optimizations but 48s for this seems a lot.

**Comment by zeenix** [comment]
After many hours of work, I gave up and took some code from toml_edit and managed to fix this issue while not breaking anything else and even fixed at least 3 ignored tests (might be a few more but I'm too tired to check all of them). I need to clean up the work next before I can create a PR.

BTW, do you have any suggestion on the easiest way to check which of the ignored tests I fixed? I guess I can always delete the whole ignore list and compare the list of failing tests with the deleted list but given the list is using wildcards, that's not so easy to automate. :)

**Comment by CosmicHorrorDev** [comment]
I've just been commenting out the ignore list and checking to see if it causes any more tests to pass, but I agree the ergonomics aren't the best. We could switch to have each ignore only match one test if you feel that's easier

**Comment by zeenix** [comment]
> We could switch to have each ignore only matching one test if you feel that's easier

Yeah, I think that'd be the best. Then we don't even need to compare. We'll just temporarily remove the list, run the tests and copy&past the list of failing tests (adding the quotes and commas, perhaps through sed or awk) back and git will tell us if there is a diff. :) Could you please do that?

**Comment by zeenix** [comment]
> Could you please do that?

No worries. Already did that (#17).

> adding the quotes and commas, perhaps through sed or awk

I did this through `sed 's/ *\(.*\)/\"\1\",/' /tmp/out`. After copy&pasting, rustfmt/editor takes care of formatting it.

**Comment by zeenix** [comment]
> If you used one test thread then the ordering would be deterministic since cargo starts tests in lexicographic order. Otherwise things are gonna shuffle around each run

Are you talking about the test case I added for this issue? If so, does that matter? One thread gets spawned that's doing the actual work and the main thread just sleeps for a while and expects the other thread to be finished by then. I know this is not 100% reliable but I unless the cpus are overloaded, this is pretty reliable still.

Also I'm not sure how cargo's threads would be relevant here, that's only about whether or not multiple tests are parallelized. It doesn't affect the threads launched by the tests themselves. Maybe I misunderstood what you meant? :thinking:

**Comment by CosmicHorrorDev** [comment]
The ordering of the ignore list will keep getting shuffled around because the tests finish in different orders. They would always finish in the same order if you ran with `cargo test -- --test--threads=1` instead
