### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }

### ISSUE THREAD

**Issue by CosmicHorrorDev** [zeenix/tomling#9]
Running #7 for a bit picked up an error when trying to parse too large of integers like the following

```toml
z=803333333333333333333333333333
```

```text
thread '<unnamed>' panicked at /home/cosmic/dev/tomling/src/parse.rs:191:49:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zeenix** [comment]
Hmm. but is this a problem? We're not crashing or overflowing the stack, but rather catching the problem. The value doesn't fit an `i64`.

**Comment by CosmicHorrorDev** [comment]
To clarify it is crashing. This input causes `parse()` to panic with the above message

**Comment by zeenix** [comment]
> To clarify it is crashing. This input causes `parse()` to panic with the above message

Ah, then yes. :) Sorry, it was still too early for me. Should be trivial to fix though (famous last words).
